frontend/app.ts, frontend/ts/ajax.ts, frontend/types/window.d.ts, package.json, webpack.config.js, yarn.lock
Momentálně prvky přidané do DOM dynamicky (skrze snippety) nefungují. Aktuálně se to týká prakticky jen alertů/flash messages, které nejdou křížkem zavřít.
=> Inicializace Bootstrap prvků ve snippetech

app/templates/@layout2.latte, app/templates/Default/about.latte, frontend/icons.ts, package.json, yarn.lock
Část #797 
Přidal jsem do patičky + upravil stránku "O projektu".
=> Odkaz na Github v Hospodaření

app/presenters/AuthPresenter.php
https://sentry.io/organizations/skautske-hospodareni-of/issues/1234396472/?project=1328535&query=is%3Aunresolved
=> set backlink default value

app/AccountancyModule/Components/templates/ChitForm.latte, app/config/webloader.neon, www/js/enter.js
Closes https://github.com/skaut/Skautske-hospodareni/issues/921
=> Odeslání formláře pro přidání/úpravu dokladu stiskem enter

app/AccountancyModule/PaymentModule/presenters/JournalPresenter.php, app/AccountancyModule/PaymentModule/templates/Journal/default.latte, app/AccountancyModule/PaymentModule/templates/Payment/default.latte, app/model/Payment/PaymentService.php
=> Oprava přehledu časopisů 

app/model/Event/Factory/CampFactory.php
https://sentry.io/organizations/skautske-hospodareni-of/issues/1246213308/?project=1328535
=> Oprava datoveho typu ze skautisu

app/AccountancyModule/Components/templates/datagrid.latte
=> Oprava responsivity u filtrů v datagridu

app/AccountancyModule/TravelModule/templates/Vehicle/new.latte
=> úprava tabulky pro harmonizovanou spotřebu

app/AccountancyModule/CampModule/presenters/DefaultPresenter.php, app/AccountancyModule/EventModule/presenters/DefaultPresenter.php
=> default grid sort

app/AccountancyModule/TravelModule/presenters/DefaultPresenter.php
opravuje https://sentry.io/organizations/skautske-hospodareni-of/issues/1354564802/?project=1328535&referrer=slack
=> check if command is null

app/AccountancyModule/Components/templates/datagrid.latte, app/AccountancyModule/Grids/GridFactory.php
Closes https://github.com/skaut/Skautske-hospodareni/issues/1130
=> Oprava resetování filtrů při změně řazení

app/model/Skautis/ParticipantRepository.php
Opravuje Sentry issue [H-SKAUTING-CZ-EM](https://sentry.io/organizations/skautske-hospodareni-of/issues/1364969802/?project=1328535&query=is%3Aunresolved)
=> Oprava zakládání účastníků bez vyplnění data narození

app/AccountancyModule/PaymentModule/components/SmtpAddForm.php, app/AccountancyModule/PaymentModule/components/SmtpUpdateForm.php, app/AccountancyModule/PaymentModule/components/templates/SmtpAddForm.latte, app/AccountancyModule/PaymentModule/components/templates/SmtpUpdateForm.latte, app/AccountancyModule/PaymentModule/factories/ISmtpAddFormFactory.php, app/AccountancyModule/PaymentModule/factories/ISmtpUpdateFormFactory.php, app/AccountancyModule/PaymentModule/presenters/MailPresenter.php, app/AccountancyModule/PaymentModule/templates/Mail/default.latte, app/model/Payment/Commands/UpdateMailPassword.php, app/model/Payment/Handlers/MailCredentials/UpdateMailPasswordHandler.php, app/model/Payment/MailCredentials.php
=> Změna SMTP hesla

app/model/Cashbook/ReadModel/QueryHandlers/Pdf/SheetChitsGenerator.php
=> Export dokladů banky v hromadném exportu

app/AccountancyModule/TravelModule/presenters/VehiclePresenter.php
VehiclePresenter nemá metodu default, protoze to se presunulo do VehicleListPresenteru
Opravuje https://sentry.io/organizations/skautske-hospodareni-of/issues/1373413627/?project=1328535&referrer=slack
=> redirect of vehicle presenter

app/model/Excel/ExcelService.php
přišli mi na to dotazy a rozhodl jsem se to hodit jen do excelu, kde si to muze kazdy odebrat sám pokud by mu to vadilo ale do pdf to dávat nechci aby se to nemuselo tisknout zbytečně
=> Přidat jednotku do excelového exportu účastníků výpravy

.docs/tipy-pro-testovani.md, app/model/Common/FilePath.php, tests/integration/Infrastructure/Services/Common/FlysystemScanStorageTest.php, tests/unit/Common/FilePathTest.php
- uniqid vrací string a ne čislo
- zkrátil jsem generovaný string, protože i tak by měl být dost náhodný pro náš účel
=> Oprava názvu scan souboru

app/AccountancyModule/PaymentModule/presenters/MailPresenter.php
ošetření https://sentry.io/organizations/skautske-hospodareni-of/issues/1408171583/?project=1328535&referrer=slack
=> check mail is not null

composer.lock
zadal jsem jen `composer update mhujer/fio-api-php` ale updatovalo to více věcí
=> composer update mhujer/fio-api-php

app/AccountancyModule/TravelModule/presenters/VehiclePresenter.php
https://sentry.io/organizations/skautske-hospodareni-of/issues/1437281847
=> Oprava špatné odchytávané výjimky při kontrole smazané jednotky

app/model/Event/ReadModel/QueryHandlers/Excel/ExportEventsHandler.php
=> Oprava dat pražských účastníků v exportu akcí

app/AccountancyModule/Components/FormControls/DateControl.php
Fix https://sentry.io/organizations/skautske-hospodareni-of/issues/1434629188
=> Přidána chybová hláška pro pole pro zadání data splatnosti

app/AccountancyModule/CampModule/templates/Detail/default.latte, app/AccountancyModule/EventModule/templates/Event/default.latte
=> Zarovnání čísel doprava

app/AccountancyModule/AccountancyHelpers.php, app/AccountancyModule/EventModule/templates/Default/@eventsGrid.latte
=> Oprava zobrazování labelů

.github/workflows/main.yml, app/AccountancyModule/PaymentModule/components/templates/PairButton.latte, app/Console/LintLatte.php, app/config/config.neon, composer.json, composer.lock, phpcs.xml
Fixuje kompatibilitu pro https://github.com/skaut/Skautske-hospodareni/pull/1214 a zároveň případný podobný chyby teď budou odhycený jinak než náhodně akceptačními testy.
=> Oprava kompatibility s Latte 2.6 + kontrola Latte šablon v CI

app/AccountancyModule/AccountancyHelpers.php, app/AccountancyModule/Components/templates/DataGrid.layout.latte, app/AccountancyModule/PaymentModule/components/GroupProgress.php, app/AccountancyModule/PaymentModule/components/PaymentList.php, app/AccountancyModule/PaymentModule/components/templates/GroupProgress.latte, app/AccountancyModule/PaymentModule/components/templates/PaymentList.grid.latte, app/AccountancyModule/PaymentModule/presenters/GroupListPresenter.php, app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php, app/AccountancyModule/PaymentModule/templates/GroupList/default.latte, app/AccountancyModule/PaymentModule/templates/Payment/default.latte, app/model/DTO/Payment/Payment.php, app/model/DTO/Payment/PaymentFactory.php, app/model/Infrastructure/Repositories/Payment/PaymentRepository.php, app/model/Payment/Handlers/Mailing/SendPaymentInfoHandler.php, app/model/Payment/MailingService.php, app/model/Payment/Payment.php, app/model/Payment/Payment/SentEmail.php, app/model/Payment/Payment/State.php, app/model/Payment/Summary.php, migrations/2020/Version20200101231338.php, tests/acceptance/PaymentCept.php, tests/integration/Infrastructure/Repositories/Payment/PaymentRepositoryTest.php, tests/unit/Payment/PaymentTest.php
Closes https://github.com/skaut/Skautske-hospodareni/issues/872
Pro platby označené jako odeslané doplníme, že má poslaný jeden email s platebními údaji s aktuálním časem (ty data nemáme a takhle aspoň uživatelům nezmizí info o tom, že posílali nějaký mail) - vyplňujeme zároveň jako uživatele "neznámý uživatel" - viz. obrázek
=> Odstranění stavu odesláno + počítadlo odeslaných emailů

app/AccountancyModule/StatisticsModule/presenter/DefaultPresenter.php, app/AccountancyModule/StatisticsModule/templates/Default/default.latte, app/AccountancyModule/presenters/DebuggingPresenter.php, app/presenters/DefaultPresenter.php, app/templates/Default/about.latte
Úprava dalších stránek na Bootstrap 4
=> Kus stránek předělán na Bootsrap 4

app/AccountancyModule/TravelModule/Components/CommandForm.php, app/AccountancyModule/TravelModule/Components/EditTravelDialog.php, app/AccountancyModule/TravelModule/presenters/CommandPresenter.php, app/AccountancyModule/TravelModule/presenters/ContractPresenter.php, app/AccountancyModule/TravelModule/presenters/DefaultPresenter.php, app/AccountancyModule/TravelModule/presenters/VehicleListPresenter.php, app/AccountancyModule/TravelModule/presenters/VehiclePresenter.php, app/AccountancyModule/TravelModule/templates/Command/default.latte, app/AccountancyModule/TravelModule/templates/Command/edit.latte, app/AccountancyModule/TravelModule/templates/Contract/default.latte, app/AccountancyModule/TravelModule/templates/Contract/detail.latte, app/AccountancyModule/TravelModule/templates/Contract/new.latte, app/AccountancyModule/TravelModule/templates/Default/detail.latte, app/AccountancyModule/TravelModule/templates/Vehicle/new.latte, app/AccountancyModule/TravelModule/templates/menu.latte, frontend/icons.ts
=> Bootstrap 4 - Travel module

codeception.yml, tests/acceptance.suite.yml, tests/acceptance/_bootstrap.php, tests/integration.suite.yml, tests/unit/_bootstrap.php
based on http://phptest.club/t/bootstrap-deprecations-in-3-0/2196
=> update codeception deprecated config

app/AccountancyModule/PaymentModule/components/PaymentDialog.php
Tohle vyplynulo z feedbacku od BRJ.
=> Oprava textu submitu při editaci platby 

app/AccountancyModule/CampModule/templates/Budget/default.latte
Řeší BC break přidaný v https://github.com/skaut/Skautske-hospodareni/pull/1286
=> Aktualizace deprecated syntaxe v Latte

app/AccountancyModule/PaymentModule/presenters/RepaymentPresenter.php, app/AccountancyModule/PaymentModule/templates/Repayment/default.latte
=> Informační box k vysvětlení vratek

.docs/instalace.md, docker-compose.yml
Jsem při mergování https://github.com/skaut/Skautske-hospodareni/pull/1294 zapomněl na tyto místa.
=> MySQL 8 v Dockeru a dokumentaci

app/AccountancyModule/Components/LoginPanel.php, app/AccountancyModule/Components/templates/LoginPanel.latte, app/templates/@layout2.latte
Nyní se nelze dostat na stránku o projektu, pokud uživatel není přihlášený.
https://sentry.io/organizations/skautske-hospodareni-of/issues/1581735540/?project=1328535&query=is%3Aunresolved+url%3Ahttps%3A%2F%2Fh.skauting.cz%2Fo-projektu
=> Přidělání části LoginPanelu pro nepřihlášené uživatele

app/AccountancyModule/TravelModule/Components/EditTravelDialog.php
Fixuje https://sentry.io/organizations/skautske-hospodareni-of/issues/1591160883/?project=1328535&referrer=slack
=> Oprava editace cesty

app/AccountancyModule/AccountancyHelpers.php, tests/unit/AccountancyHelpersTest.php
upravil jsem `postCode` a umazal nepoužívanou metodu
=> Nové testy pro helpery

app/AccountancyModule/Components/templates/LoginPanel.latte, app/config/config.ci.local.neon, app/config/config.neon, app/config/config.sample.local.neon, app/config/config.test.local.neon, app/presenters/BasePresenter.php, app/templates/@layout2.latte, frontend/app.scss
=> Žlutá navigace pro testovací prostředí

app/AccountancyModule/PaymentModule/components/templates/PaymentList.grid.latte, app/model/Bank/BankService.php, app/model/DTO/Payment/Payment.php, app/model/DTO/Payment/PaymentFactory.php, app/model/Payment/Payment.php, app/model/Payment/PaymentService.php, migrations/2020/Version20200410190351.php, tests/integration/Payment/UseCases/PaymentCompletedEmailTest.php, tests/integration/PaymentServiceTest.neon, tests/unit/Payment/PaymentTest.php
close #1279 
Přidal jsem sloupeček do databáze, kam se uloží jméno osoby co to uzavřela.
=> Přidáno jméno uživatele, který dokončil platbu

.docs/instalace.md
Close https://github.com/skaut/Skautske-hospodareni/issues/956
=> Zdokumentována možnost vypnutí opravy CS

app/AccountancyModule/CampModule/templates/header.latte, app/AccountancyModule/Components/Cashbook/templates/ChitListControl.latte, app/AccountancyModule/EventModule/templates/header.latte, app/AccountancyModule/UnitAccountModule/templates/header.latte, app/templates/@layout2.latte, frontend/app.scss
- přidáno odsazení u akcí
- opravena ikona v evidenci plateb
- oprava menu v testovací verzi
=> Oprava zobrazení

app/AccountancyModule/Components/Cashbook/templates/ChitListControl.latte
zapomenutá tečka mezi měsícem a rokem
=> fix year separator

app/AccountancyModule/CampModule/presenters/BasePresenter.php, app/AccountancyModule/EventModule/presenters/BasePresenter.php, app/AccountancyModule/EventModule/presenters/NewEventPresenter.php, app/AccountancyModule/PaymentModule/presenters/BankAccountsPresenter.php, app/AccountancyModule/PaymentModule/presenters/BasePresenter.php, app/AccountancyModule/PaymentModule/presenters/GroupPresenter.php, app/AccountancyModule/PaymentModule/presenters/JournalPresenter.php, app/AccountancyModule/PaymentModule/presenters/MailPresenter.php, app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php, app/AccountancyModule/TravelModule/presenters/ContractPresenter.php, app/AccountancyModule/TravelModule/presenters/DefaultPresenter.php, app/AccountancyModule/TravelModule/presenters/VehiclePresenter.php, app/AccountancyModule/UnitAccountModule/presenters/BasePresenter.php, app/AccountancyModule/presenters/BasePresenter.php, app/AccountancyModule/templates/accessDenied.latte, docker-compose.override.yml
close #1238 
Nově se bude zobrazovat stránka upozoněním namísto přesměrování
Stránka není nejkrásnější ale tedka jde o funkci, která pomůže. Vzhled lze upravovat kdykoliv. 
Nevím jestli jsem našel všechny místa, kde se to může hodit, ale opět bych je upravil až zjistím, že to někde chybí.
=> Zobrazení chybové stránky místo přesměrování

app/model/Cashbook/Cashbook/CashbookId.php, migrations/2020/Version20200411105206.php, tests/integration/Cashbook/CashbookIntegrationTest.php, tests/integration/Cashbook/Handlers/MoveChitsToDifferentCashbookHandlerTest.php, tests/integration/Cashbook/ReadModel/QueryHandlers/ChitListQueryHandlerTest.php, tests/integration/Infrastructure/Repositories/Cashbook/CashbookRepositoryTest.php, tests/integration/Infrastructure/Repositories/Cashbook/UnitRepositoryTest.php, tests/unit/Cashbook/Cashbook/CashbookIdTest.php, tests/unit/Cashbook/CashbookTest.php, tests/unit/Cashbook/Handlers/CashbookHandlersTest.php, tests/unit/Cashbook/Handlers/CreateCashbookHandlerTest.php, tests/unit/Cashbook/ReadModel/CategoryPairsQueryHandlerTest.php, tests/unit/Cashbook/ReadModel/ChitQueryHandlerTest.php, tests/unit/Cashbook/ReadModel/FinalBalanceQueryHandlerTest.php, tests/unit/Cashbook/ReadModel/FinalRealBalanceQueryHandlerTest.php, tests/unit/Cashbook/Repositories/CategoryRepositoryTest.php, tests/unit/Cashbook/UnitTest.php
=> Migrace cashbookId z int na UUIDv4

app/AccountancyModule/EventModule/templates/Event/default.latte, app/templates/Tutorial/event.latte
=> Odebrání upozornění

app/AccountancyModule/StatisticsModule/templates/Default/default.latte, app/model/Export/templates/cashbook.latte, app/model/Export/templates/chitlist.latte
pak znovu pustit https://github.com/skaut/Skautske-hospodareni/pull/1322
=> Příprava pro latte 2.7

app/AccountancyModule/PaymentModule/templates/Payment/default.latte, tests/_support/Page/Payment.php
=> Seskupení tlačítek

app/AccountancyModule/Components/templates/LoginPanel.latte, app/templates/Default/default.latte
- login jako primary
- ostatni odkazy na secondary nebo odebrany pokud jsou na tutorialy
=> Login tlačítko jako primární akce

app/AccountancyModule/Components/Cashbook/ChitListControl.php, app/AccountancyModule/Components/Cashbook/ChitScanControl.php, app/AccountancyModule/Components/Cashbook/templates/ChitListControl.latte, app/AccountancyModule/Components/Cashbook/templates/ChitListControl.topPanel.latte, app/AccountancyModule/Components/Cashbook/templates/ChitScanControl.latte, app/AccountancyModule/Factories/Cashbook/IChitScanControlFactory.php, app/AccountancyModule/TravelModule/Components/templates/RoadworthyControl.latte, app/AccountancyModule/presenters/CashbookExportPresenter.php, app/model/Cashbook/Commands/Cashbook/RemoveChitScan.php, app/model/Cashbook/ReadModel/Queries/CashbookScansQuery.php, app/model/Cashbook/ReadModel/QueryHandlers/CashbookScansQueryHandler.php, app/model/Common/FilePath.php, app/model/DTO/Cashbook/Chit.php, composer.json, composer.lock, frontend/icons.ts, frontend/ts/ChitListExtension.ts, frontend/ts/ajax.ts
=> Počet naskenovaných dokladů

app/AccountancyModule/CampModule/CampListDataSource.php, app/AccountancyModule/CampModule/presenters/BasePresenter.php, app/AccountancyModule/CampModule/presenters/DetailPresenter.php, app/AccountancyModule/Components/Cashbook/ChitListControl.php, app/AccountancyModule/Components/Cashbook/PrefixControl.php, app/AccountancyModule/Components/Cashbook/templates/ChitListControl.topPanel.latte, app/AccountancyModule/Components/Cashbook/templates/PrefixControl.latte, app/AccountancyModule/Components/CashbookControl.php, app/AccountancyModule/Components/ChitForm.php, app/AccountancyModule/Components/templates/CashbookControl.latte, app/AccountancyModule/EventModule/EventListDataSource.php, app/AccountancyModule/EventModule/presenters/BasePresenter.php, app/AccountancyModule/EventModule/presenters/EventPresenter.php, app/AccountancyModule/Factories/Cashbook/IPrefixControlFactory.php, app/model/Cashbook/Cashbook.php, app/model/Cashbook/Commands/Cashbook/UpdateChitNumberPrefix.php, app/model/Cashbook/Handlers/Cashbook/UpdateChitNumberPrefixHandler.php, app/model/Cashbook/ReadModel/QueryHandlers/CashbookQueryHandler.php, app/model/Cashbook/ReadModel/QueryHandlers/Pdf/SheetChitsGenerator.php, app/model/Cashbook/ReadModel/QueryHandlers/Pdf/templates/chits.hpd.latte, app/model/Cashbook/ReadModel/QueryHandlers/Pdf/templates/chits.in.latte, app/model/Cashbook/ReadModel/QueryHandlers/Pdf/templates/chits.out.latte, app/model/DTO/Cashbook/Cashbook.php, app/model/Event/ReadModel/QueryHandlers/Excel/ExportEventsHandler.php, app/model/Excel/ExcelService.php, app/model/Export/ExportService.php, migrations/2020/Version20200508102927.php, tests/integration/Infrastructure/Repositories/Cashbook/CashbookRepositoryTest.php, tests/unit/Cashbook/CashbookTest.php, tests/unit/Cashbook/Handlers/CashbookHandlersTest.php
=> Prefix jako součást seznamu dokladů

app/AccountancyModule/Components/Cashbook/templates/ChitScanControl.latte, app/AccountancyModule/TravelModule/Components/templates/RoadworthyControl.latte, app/model/Cashbook/ReadModel/QueryHandlers/CashbookScansQueryHandler.php, app/model/Common/FilePath.php
opravuje https://sentry.io/organizations/skautske-hospodareni-of/issues/1675765629/?project=1328535&referrer=slack
=> Oprava názvu

app/AccountancyModule/Components/Cashbook/templates/ChitListControl.latte
=> Oprava hromadného zaškrtávání checkboxů v evidenci plateb 

app/AccountancyModule/Components/Participants/ParticipantList.php
V případě, že je pro účet použito `Ponechat původní hodnotu` tak to spadlo viz https://sentry.io/organizations/skautske-hospodareni-of/issues/1688553349/?project=1328535
=> Oprava hromadné úpravy účastníků

.github/workflows/main.yml, app/AccountancyModule/Components/Participants/templates/ParticipantList.latte
=> Oprava seznamu účastníků

.github/workflows/main.yml
Pro snazší debuggování (např. v #1385)
=> Ukládání artefaktů k chybám v akceptačních testech

app/AccountancyModule/Components/Participants/ParticipantList.php, app/bootstrap.php
=> Oprava řezení účastníků

app/AccountancyModule/CampModule/presenters/DetailPresenter.php, app/AccountancyModule/CampModule/templates/Detail/default.latte
https://sentry.io/organizations/skautske-hospodareni-of/issues/1694764872/?project=1328535&referrer=slack
Když se volá závěrečná zpráva ale chybí kategorie, tak se nově zobrazí komponenta na aktivaci automatického dopočítávání.
=> Oprava závěrečné zprávy u táborů

.docs/instalace.md, app/AccountancyModule/Components/DataGrid.php, docker-compose.yml, tests/acceptance.suite.yml, tests/integration/fixtures/UnitRepository/findByParent.json, tests/integration/fixtures/UnitRepository/findByParent_empty.json
=> disable autocomplete

app/model/DTO/Cashbook/ChitFactory.php
Může to nastat, kdyz si udela u tabora kategorii, hodí do ní doklad a pak kategorii smaže. tedy málo pravděpodobné a řešil bych to zatím opravou v datech. Chci radeji tuto konkretní vyjímku
=> Chybějící kategorie

app/AccountancyModule/Components/Participants/templates/ParticipantList.latte
=> Formátování čátek u účastníků

app/model/Skautis/Payment/MemberEmailRepository.php, tests/integration/Skautis/Payment/MemberEmailRepositoryTest.php, tests/integration/_bootstrap.php, tests/integration/fixtures/Payment/MemberEmailRepository/findByMember.json, tests/integration/fixtures/Payment/MemberEmailRepository/findByMember_empty.json, tests/integration/fixtures/Payment/MemberEmailRepository/findByMember_noPermission.json
close #1461
Oprava po změně ve skautisu, kde je potřeba volat odděleně seznam rodičovských emailů
=> Přidání rodičovských emailů

app/AccountancyModule/TravelModule/Components/EditTravelDialog.php, app/AccountancyModule/TravelModule/templates/Default/detail.latte
=> Překreslení tabulky cest po editaci

app/AccountancyModule/Components/ChitForm.php, app/model/Cashbook/ReadModel/QueryHandlers/FinalRealBalanceQueryHandler.php, app/model/Skautis/Cashbook/CampCategoryUpdater.php, app/model/Skautis/Exception/AmountMustBeGreaterThanZero.php, tests/unit/Cashbook/ReadModel/FinalRealBalanceQueryHandlerTest.php
=> Oprava počítání táborových vratek

app/AccountancyModule/CampModule/templates/Budget/default.latte
close #1465 
navrácení zpět proměnné, která byla asi omylem odebrána zde https://github.com/skaut/Skautske-hospodareni/commit/2c15ee670c18fe39c929ac3cb4e443991c3773c7#diff-2943dabc7cf0d6c37874ee6a04783e78L55
=> fix inconsistent camp categories

app/AccountancyModule/CampModule/presenters/CashbookPresenter.php, app/AccountancyModule/CampModule/presenters/DetailPresenter.php, app/AccountancyModule/CampModule/templates/Cashbook/default.latte, app/AccountancyModule/CampModule/templates/Detail/default.latte
Nyní web hází chybu 500
https://sentry.io/organizations/skautske-hospodareni-of/issues/1918448147/?referrer=slack
=> Zachycení chybějících kategorií

app/model/Cashbook/Cashbook/Chit.php, tests/integration/Cashbook/Handlers/MoveChitsToDifferentCashbookHandlerTest.neon, tests/integration/Cashbook/Handlers/MoveChitsToDifferentCashbookHandlerTest.php
Fixes https://github.com/skaut/Skautske-hospodareni/issues/1478
=> Oprava přesouvání dokladů se skeny

app/AccountancyModule/CampModule/presenters/BasePresenter.php, app/AccountancyModule/EventModule/presenters/BasePresenter.php, app/AccountancyModule/EventModule/presenters/CashbookPresenter.php
Nyní se přistupuje k $this->event i ve chvíli kdy je jasné, že je null a bude zobrazena hláška, že nemá přístup. 
https://sentry.io/organizations/skautske-hospodareni-of/issues/1799901307/?project=1328535&referrer=slack
https://sentry.io/organizations/skautske-hospodareni-of/issues/1907210026/?project=1328535&referrer=slack
=> Kontrola že event je načtena

app/AccountancyModule/Components/Participants/ParticipantList.php, app/AccountancyModule/Components/Participants/templates/ParticipantList.latte
=> Oprava zobrazení tabulky účastníků

app/model/Export/ExportService.php, app/model/Export/templates/campReport.latte
=> Přidat výsledek hospodaření do táborového pdf exportu

composer.json, composer.lock
Používá se v #1427, navrhuju mergnout samostatně, ať ten PR není potřeba neustále rebasovat při mergování PRs od Dependabota.
=> Přidání Google SDK klienta

app/AccountancyModule/PaymentModule/templates/Mail/default.latte
=> Změna textu přes jaké emaily se dá přihlásit

app/AccountancyModule/Components/Cashbook/ChitScanControl.php
u uzavřených/odevzdaných táborů je poptávka po možnosti dodatečně přidat sken
=> Povolit přidat skeny k uzavřené pokladní knize

app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php, app/AccountancyModule/PaymentModule/templates/Payment/massAdd.latte, app/model/Payment/ReadModel/Queries/MembersWithoutPaymentInGroupQuery.php, app/model/Payment/ReadModel/QueryHandlers/MembersWithoutPaymentInGroupQueryHandler.php, app/presenters/BasePresenter.php, tests/unit/Payment/ReadModel/QueryHandlers/MembersWithoutPaymentInGroupQueryHandlerTest.php
=> Zobrazení členů podjednotek v platbách

app/AccountancyModule/PaymentModule/components/PaymentList.php, app/AccountancyModule/PaymentModule/components/templates/PaymentList.grid.latte, app/model/DTO/Payment/Payment.php
aktuálně data grid hodí chybu při pokusu o řazení dle emailu, protoze getEmail neexistuje na PaymentDTO
https://sentry.io/organizations/skautske-hospodareni-of/issues/2102581463/?project=1328535&referrer=slack
=> fix payment data grid sorting

app/model/Participant/Payment/Event.php
https://sentry.io/organizations/skautske-hospodareni-of/issues/2105851756/?project=1328535
=> fix hydratation

app/AccountancyModule/TravelModule/Components/CommandForm.php
close https://sentry.io/organizations/skautske-hospodareni-of/issues/2104613749/?project=1328535
=> fix commands form

app/AccountancyModule/TravelModule/Components/CommandForm.php
řeší https://sentry.io/organizations/skautske-hospodareni-of/issues/2107646055/?project=1328535&referrer=slack
=> fix travel command

app/model/Payment/ReadModel/QueryHandlers/RepaymentCandidateListQueryHandler.php
opravuje https://sentry.io/organizations/skautske-hospodareni-of/issues/2106762021/?project=1328535&referrer=slack
=> fix repayment check

app/config/config.neon, app/model/Infrastructure/Skautis/LazyWebService.php, app/model/Skautis/WebserviceFactory.php, composer.json, composer.lock, tests/unit/Infrastructure/Skautis/LazyWebServiceTest.php
Nakonec jsem se rozhodl jít jednodušší cestou než použitím ProxyManageru. Tím, že potřebujeme lazy proxy jen pro jeden interface `WebServiceInterface`, mi přišlo jednodušší ji přímo implementovat.
Je to sice jeden extra test (resp 3), ale zas je to o jednu přímou závislost méně.
=> Odebrání lookyman/nette-proxy

build.xml
Tohle jsem zapomněl odebrat v #1569
=> Odebrání neexistujícího commandu z deploymentu

app/AccountancyModule/PaymentModule/presenters/AddRegistrationMembersPresenter.php, app/AccountancyModule/PaymentModule/presenters/CreateRegistrationGroupPresenter.php, app/AccountancyModule/PaymentModule/templates/AddRegistrationMembers/default.latte, app/AccountancyModule/PaymentModule/templates/CreateRegistrationGroup/default.latte, app/AccountancyModule/PaymentModule/templates/GroupList/default.latte, app/AccountancyModule/PaymentModule/templates/Payment/default.latte
=> Rozdělení registrace do samostatných presenterů

app/AccountancyModule/PaymentModule/presenters/AddRegistrationMembersPresenter.php
=> Odebrání osob s nulovou platbou

app/model/Bank/BankService.php, app/model/Bank/Fio/FioClient.php, app/model/Payment/BankAccountService.php, app/model/Payment/Fio/CachingClientDecorator.php, app/model/Payment/Fio/IFioClient.php, tests/unit/Bank/Fio/FioClientTest.php, tests/unit/BankServiceTest.php
=> Oprava špatného časového rozsahu při párování více skupin, kdy jedna nebyla párována

app/AccountancyModule/CampModule/presenters/BasePresenter.php, app/AccountancyModule/EventModule/presenters/BasePresenter.php
aktuálně se pro vyrenderování stránky Access denied kontrolovali věci v stratup(), které ale reálně nejsou pro tuto stránku potřeba a ani nastavené.
=> fix access denied rendering

app/model/Skautis/Cashbook/CampCategoryUpdater.php
https://sentry.io/organizations/skautske-hospodareni-of/issues/2234007975/?project=1328535&query=is%3Aunresolved
=> fix campId

app/model/Payment/Payment/Transaction.php
https://sentry.io/organizations/skautske-hospodareni-of/issues/2272349557/?project=1328535&query=is%3Aunresolved
=> fix init payer

app/AccountancyModule/PaymentModule/presenters/BankAccountsPresenter.php
řeší https://sentry.io/organizations/skautske-hospodareni-of/issues/2298429081/?project=1328535&query=is%3Aunresolved
=> inicializace bank account id

app/AccountancyModule/PaymentModule/components/templates/PairButton.latte, app/AccountancyModule/PaymentModule/templates/BankAccounts/default.latte
u disabled tlačítek je potřeba zadat tooltip na obalující prvek
=> Přidat disabled a tooltip kdyz není dostatečné oprávnění

app/AccountancyModule/PaymentModule/presenters/RepaymentPresenter.php, app/model/DTO/Payment/RepaymentCandidate.php, app/model/DTO/Payment/RepaymentCandidateFactory.php, app/model/Payment/ReadModel/QueryHandlers/RepaymentCandidateListQueryHandler.php, tests/unit/Payment/ReadModel/QueryHandlers/RepaymentCandidateListQueryHandlerTest.php
=> Oprava vratek pro platby bez navázané osoby

app/model/Event/ReadModel/QueryHandlers/EducationListQueryHandler.php
close https://github.com/skaut/Skautske-hospodareni/issues/1603
=> Vyfiltrovat vzdělávací akce kde jsem v týmu

app/AccountancyModule/TravelModule/presenters/DefaultPresenter.php, app/AccountancyModule/TravelModule/templates/Default/detail.latte, app/model/Travel/Command.php, app/model/Travel/Commands/Command/DuplicateTravel.php, app/model/Travel/Handlers/Command/DuplicateTravelHandler.php, frontend/icons.ts, tests/unit/Travel/CommandTest.php
=> Duplikování cest v cesťácích

app/config/config.neon, build.xml
Closes #1712
Vysvětlení fixu viz https://github.com/skaut/Skautske-hospodareni/issues/1712#issuecomment-967030898
Tohle jsem ještě rozbil v #1679
=> Oprava pouštění konzolových příkazů v rámci deploymentu 

composer.json, composer.lock, phpstan.neon, tests/acceptance/CashbookTest.php
Motivací je především podpora novějších verzí PHP
=> Aktualizace Codeception

app/model/Common/Services/MessengerEventBus.php
https://sentry.io/organizations/skautske-hospodareni-of/issues/2917267990/?project=1328535&referrer=slack
=> Oprava - zpracování správné vyjímky

app/AccountancyModule/AccountancyHelpers.php, app/AccountancyModule/EducationModule/presenters/ParticipantPresenter.php, app/model/Event/Education.php, app/model/Event/Factory/EducationFactory.php, app/model/Export/ExportService.php, app/model/Export/templates/participantEducation.latte
- allow Start and End date as null
- oprava exportu ucastniku
=> Oprava education modulu

app/model/Cashbook/ReadModel/QueryHandlers/CashbookDisplayNameQueryHandler.php
https://sentry.io/organizations/skautske-hospodareni-of/issues/2950899133/?project=1328535&referrer=slack
=> add education type

app/AccountancyModule/TravelModule/Components/RoadworthyControl.php
Close https://github.com/skaut/Skautske-hospodareni/issues/1829
=> Oprava odebrani skenu technického průkazu

app/AccountancyModule/TravelModule/templates/Default/ex.command.latte
=> Přejmenování položky v exportu cestovního příkazu

.docs/tipy-pro-testovani.md, app/AccountancyModule/PaymentModule/RegistrationModule/templates/AddMembers/default.latte, app/AccountancyModule/PaymentModule/components/GroupForm.php, app/AccountancyModule/PaymentModule/components/PaymentDialog.php, app/AccountancyModule/PaymentModule/components/PaymentList.php, app/AccountancyModule/PaymentModule/components/templates/GroupForm.latte, app/AccountancyModule/PaymentModule/components/templates/PaymentDialog.latte, app/AccountancyModule/PaymentModule/components/templates/PaymentList.grid.latte, app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php, app/AccountancyModule/PaymentModule/templates/@layout.latte, app/AccountancyModule/PaymentModule/templates/Mail/default.latte, app/AccountancyModule/PaymentModule/templates/Payment/default.latte, app/AccountancyModule/PaymentModule/templates/defaultEmails/payment_completed.html, app/AccountancyModule/PaymentModule/templates/defaultEmails/payment_info.html, app/model/Export/templates/campReport.latte, app/model/Export/templates/educationReport.latte, app/model/Export/templates/eventReport.latte, app/model/Payment/Exception/PaymentHasNoEmails.php, app/model/Payment/MailingService.php, app/model/emails/oAuthAdded.latte, tests/_support/Page/Payment.php, tests/acceptance/PaymentCept.php, tests/integration/Payment/stubs/NullMailer.php
=> Oprava email na e-mail

app/model/Excel/Builders/CashbookWithCategoriesBuilder.php
opravuje https://sentry.io/organizations/skautske-hospodareni-of/issues/3248851887/?project=1328535&referrer=slack
=> fix cell range

app/AccountancyModule/PaymentModule/components/templates/GroupForm.latte, app/model/Payment/EmailTemplate.php, tests/unit/Payment/Group/EmailTemplateTest.php
=> Přidání makra po automatické plnění dat do Google formuláře. 

app/model/Excel/Builders/CashbookWithCategoriesBuilder.php
Removing number highlighted in red.
=> remove meaningless sum in excel export

app/AccountancyModule/Components/Cashbook/templates/ChitScanControl.latte
closes https://github.com/skaut/Skautske-hospodareni/issues/2001
=> show files on mobile

app/AccountancyModule/PaymentModule/presenters/GroupListPresenter.php
aktuálně zrušená jednotka blokuje výpis seznamu jednotek, protoze nebyla osetrena vyjímka
=> handle unit not found exception

app/model/Cashbook/ReadModel/QueryHandlers/Pdf/templates/chits.in.latte, app/model/Cashbook/ReadModel/QueryHandlers/Pdf/templates/chits.latte, app/model/Cashbook/ReadModel/QueryHandlers/Pdf/templates/chits.out.latte
closes https://github.com/skaut/Skautske-hospodareni/issues/1985
=> Oprava formátování exportovaných dokladů s dlouhými texty

app/AccountancyModule/TravelModule/Components/CommandGrid.php, app/AccountancyModule/TravelModule/presenters/CommandPresenter.php, app/AccountancyModule/TravelModule/templates/Default/detail.latte
=> 2015 error 404 při pokusu o úpravu cesťáku

app/AccountancyModule/PaymentModule/components/PaymentNoteDialog.php, app/AccountancyModule/PaymentModule/components/templates/PaymentList.grid.latte, app/AccountancyModule/PaymentModule/components/templates/PaymentNoteDialog.latte, app/AccountancyModule/PaymentModule/factories/IPaymentNoteDialogFactory.php, app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php, app/AccountancyModule/PaymentModule/templates/Payment/default.latte, app/model/Payment/Commands/Payment/UpdateNote.php, app/model/Payment/Handlers/Payment/UpdateNoteHandler.php, app/model/Payment/Payment.php
=> 1672 Editovatelná poznámka u každé platby

app/AccountancyModule/TravelModule/templates/Default/detail.latte
Na mobilu nejde vytisknout / stáhnout PDF cestovního příkazu.
=> Travel command: allow to print pdf from mobile devices

app/AccountancyModule/AccountancyHelpers.php
https://www.pravopisne.cz/2010/11/data-x-datumy/
=> Fixed grammar (datum - data)

app/model/Cashbook/ReadModel/QueryHandlers/CashbookOfficialUnitQueryHandler.php
=> Opravena chyba exportu pokladní knihy vzdělávačky

app/AccountancyModule/EducationModule/presenters/CashbookPresenter.php, app/AccountancyModule/EducationModule/templates/Cashbook/default.latte, app/model/Cashbook/ReadModel/Queries/EducationParticipantCategoryIdQuery.php, app/model/Cashbook/ReadModel/QueryHandlers/EducationParticipantCategoryIdQueryHandler.php
=> Přidáno načítání účastnických poplatků přes HPD k vzdělávačkám

app/model/Event/Factory/EducationFactory.php
=> Using education event name without course names

app/model/Participant/Factory/ParticipantFactory.php
=> Opraveno parsování jednotek účastníků vzdělávacích akcí

app/AccountancyModule/EducationModule/EducationListDataSource.php, app/AccountancyModule/EducationModule/presenters/DefaultPresenter.php, app/AccountancyModule/EducationModule/templates/Default/@eventsGrid.latte, app/model/DTO/Education/EducationListItem.php
- Přidal jsem třídu `EducationListItem` po vzoru `CampListItem`
- Je to malý PR, spíš jsem se chtěl zorientovat v codebase, rád bych ty vzdělávačky trochu posunul...
Closes #2314 , closes #2315
=> Přidán prefix a vyhledávání podle názvu do seznamu vzdělávaček

app/model/Event/Factory/EducationFactory.php
@sinacek Opravuje chybu z produkce z dnešního dopoledne.
=> Fixed error caused by IS not returning any grant ID for education event

app/AccountancyModule/EducationModule/presenters/PrivilegesPresenter.php
Mám o tom dost silný pochyby, ale možná to opraví #2361... Nicméně i kdyby ne, tak to aspoň sjednotí kód...
=> Maybe fix education privilege display

app/AccountancyModule/CampModule/presenters/ParticipantPresenter.php, app/AccountancyModule/Components/Participants/EditParticipantDialog.php, app/AccountancyModule/Components/Participants/ParticipantList.php, app/AccountancyModule/EducationModule/presenters/ParticipantPresenter.php, app/AccountancyModule/EventModule/presenters/ParticipantPresenter.php, app/AccountancyModule/Factories/Participants/IParticipantListFactory.php, app/model/DTO/Participant/Participant.php, app/model/DTO/Participant/ParticipantFactory.php, app/model/DTO/Participant/UpdateParticipant.php, app/model/Event/Camp.php, app/model/Event/Factory/CampFactory.php, app/model/Participant/Exception/ParticipantNotFound.php, app/model/Participant/Factory/ParticipantFactory.php, app/model/Participant/Participant.php, app/model/Participant/ParticipantService.php
Přidání parametru IsAccepted povinného pro skautIs.
Pro hrmomadné úpravy vypisuje seznam účastníků, které nejde editovat
Chybový výpis
Editace jednotlivce
=> 2215 nefunguje aktualizace ucastnika tabora

tests/acceptance/CashbookTest.php, tests/acceptance/PaymentCept.php
Kvůli změně rozložení některých prvku již nejsou na testovaném rozlišení prvky ve viditelné oblasti.
=> Fix acceptance test - scroll windows to expected elements

app/AccountancyModule/EducationModule/presenters/EducationPresenter.php, app/AccountancyModule/EducationModule/templates/Education/default.latte, app/model/Event/EducationLocation.php, app/model/Event/Factory/EducationLocationFactory.php, app/model/Event/ReadModel/Queries/EducationLocationsQuery.php, app/model/Event/ReadModel/QueryHandlers/EducationLocationsQueryHandler.php, app/model/Event/SkautisEducationLocationId.php
Pořád to může přetéct, ale už tam nebudou zbytečné informace navíc...
Closes #2368
=> Zobrazování krátkých názvů míst vzdělávaček

app/AccountancyModule/AccountancyHelpers.php, app/AccountancyModule/EducationModule/presenters/EducationPresenter.php, app/AccountancyModule/EducationModule/templates/Education/default.latte, app/model/Event/Education.php, app/model/Event/Factory/EducationFactory.php, app/model/Grant/Factory/GrantFactory.php, app/model/Grant/Grant.php, app/model/Grant/ReadModel/Queries/GrantQuery.php, app/model/Grant/ReadModel/QueryHandlers/GrantQueryHandler.php, app/model/Grant/SkautisGrantId.php
Ne všema položkama jsem si jistej, protože v test-ISu nemůžu hýbat s dotací do všech stavů... Ale po nasazení kdyžtak opravím.
Closes #2359
=> Přidány informace o dotaci do základní obrazovky vzdělávací akce

app/AccountancyModule/CampModule/presenters/ParticipantPresenter.php, app/AccountancyModule/EducationModule/presenters/CashbookPresenter.php, app/AccountancyModule/EducationModule/presenters/EducationPresenter.php, app/AccountancyModule/EducationModule/presenters/ParticipantPresenter.php, app/AccountancyModule/EducationModule/presenters/PrivilegesPresenter.php, app/AccountancyModule/EducationModule/templates/Education/default.latte, app/AccountancyModule/EventModule/presenters/ParticipantPresenter.php, app/model/Auth/Resources/Education.php, app/model/Auth/Resources/Grant.php, app/model/Skautis/Auth/SkautisAuthorizator.php
Stránka s účastníky a doklady se odmítne otevřít, ale vyhodí srozumitelnou chybovku. Základní stránku mi přišlo dobrý zobrazit, ale některý informace nejde zobrazit - zatím jsem je prostě nechal prázdný, kdybyste měli nápad na lepší řešení, beru...
Closes #2362
=> Opraveny chyby při zobrazování vzdělávaček bez oprávnění

app/AccountancyModule/EducationModule/presenters/EducationPresenter.php, app/AccountancyModule/EducationModule/templates/Education/default.latte, app/model/Grant/Factory/GrantFactory.php, app/model/Grant/Grant.php
No, tak to na první dobrou nebylo úplně přehledný :D
=> Logičtější informace o dotacích

app/AccountancyModule/EducationModule/presenters/EducationPresenter.php, app/model/Event/Education.php, app/model/Event/EducationTerm.php, app/model/Event/Factory/EducationFactory.php, app/model/Export/ExportService.php, app/model/Export/templates/educationReport.latte
Přidání dalších údajů o akci do závěrečné zprávy vzdělávačky, po vzoru #2303.
- Porádající jednotka
- Počet dnů
- Místa konání
- Počet účastníků
- Počet osobodnů
Closes #2334. Závisí na #2303
=> Přidány informace do závěrečné zprávy vzdělávačky

app/AccountancyModule/EducationModule/presenters/ParticipantPresenter.php, app/model/Excel/ExcelService.php, app/model/Export/templates/participantEducation.latte, app/model/Participant/Factory/ParticipantFactory.php
- Opravena data narození
- Přidány sloupce vratek, celkových poplatků a indikátorů platby na účet
- Přidán řádek sum na konec exportu
- PDF export na šířku
- Šablona excelových exportů pro vzdělávačky, obsahující jen relevantní sloupce
Closes #2335. Obsoletes #2340.
=> Rozšířeny exporty účastníků vzdělávačky

app/model/Export/templates/participantEducation.latte
=> Fixed education participant export table width

app/model/Participant/ReadModel/Queries/EducationParticipantListQuery.php, app/model/Participant/ReadModel/QueryHandlers/EducationParticipantListQueryHandler.php
=> Filtrování účastníků vzdělávaček v query

app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php
Nefungující export selže tiše a nezanechá nikde log, podle kterého by se dalo něco vyřešit.
=> Add log to export handle

app/AccountancyModule/CampModule/Factories/IMissingAutocomputedCategoryControlFactory.php, app/AccountancyModule/EducationModule/presenters/BudgetPresenter.php, app/AccountancyModule/EducationModule/templates/Budget/default.latte, app/AccountancyModule/EducationModule/templates/header.latte, app/config/config.neon, app/model/Cashbook/Commands/Cashbook/UpdateEducationCategoryTotals.php, app/model/Cashbook/Handlers/Cashbook/UpdateEducationCategoryTotalHandler.php, app/model/Cashbook/ReadModel/Queries/InconsistentEducationCategoryTotalsQuery.php, app/model/Cashbook/ReadModel/QueryHandlers/InconsistentEducationCategoryTotalsQueryHandler.php, app/model/Cashbook/Services/IEducationCategoryUpdater.php, app/model/Grant/SkautisGrantId.php, app/model/Skautis/Cashbook/EducationCategoryUpdater.php, app/model/Skautis/Cashbook/Repositories/EducationCategoryRepository.php, app/model/Skautis/ReadModel/Queries/EducationBudgetQuery.php, app/model/Skautis/ReadModel/QueryHandlers/EducationBudgetQueryHandler.php, app/router/RouterFactory.php
Přidán rozpočet po vzoru táborů i k vzdělávačkám. Musí předtím být mergnutý #2303 a #2360 , tohle z nich přepoužívá věci...
Closes #2310
=> Přidána záložka rozpočtu pro vzdělávací akce

app/AccountancyModule/EducationModule/presenters/BudgetPresenter.php, app/AccountancyModule/EducationModule/presenters/CashbookPresenter.php, app/AccountancyModule/EducationModule/presenters/PrivilegesPresenter.php, app/model/Auth/Resources/Education.php, app/model/Auth/Resources/Grant.php
=> Opravena oprávnění pro úpravu skutečného rozpočtu vzdělávaček

app/AccountancyModule/EducationModule/presenters/BudgetPresenter.php, app/AccountancyModule/EducationModule/presenters/CashbookPresenter.php
=> Opraveno používání neexistujícího grantu vzdělávačky

migrations/2023/Version20231027085506.php
=> Sjednocení charsetů a collation v databázi

app/AccountancyModule/EducationModule/EducationListDataSource.php, app/AccountancyModule/EducationModule/presenters/BudgetPresenter.php, app/AccountancyModule/EducationModule/presenters/CashbookPresenter.php, app/AccountancyModule/EducationModule/presenters/EducationPresenter.php, app/AccountancyModule/EducationModule/presenters/ParticipantPresenter.php, app/AccountancyModule/EducationModule/templates/Budget/default.latte
=> Opravy corner-cases pro vzdělávačky bez termínů nebo bez dotace

app/AccountancyModule/Components/templates/LoginPanel.latte, app/templates/@layout.latte
Ad #2426
Teď když je ta role moc dlouhá, tak to přeteče - to taky není úplně ideální, ale to už neumím opravit. Takže se na to buď prosím koukněte někdo, kdo umíte s `display: flex`, nebo navrhuju to mergnout takhle, rozhodně to je vylepšení oproti současnému stavu.
=> Částečně opraveno zalamování hlavního menu

app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php
=> escape excel sheet name

app/model/Cashbook/ReadModel/QueryHandlers/CashbookScansQueryHandler.php
close https://github.com/skaut/Skautske-hospodareni/issues/2449
=> fix encoding

app/AccountancyModule/Components/Cashbook/templates/ChitScanControl.latte
nezobrazuje se ikonka na nahrání scanu dokladu
=> remove d-none

app/AccountancyModule/Components/Cashbook/MoveChitsDialog.php, app/AccountancyModule/Components/Cashbook/templates/MoveChitsDialog.latte, app/AccountancyModule/EventModule/templates/Event/default.latte, app/AccountancyModule/UnitAccountModule/Components/templates/ActivateCashbookDialog.latte, app/AccountancyModule/UnitAccountModule/Components/templates/CreateCashbookDialog.latte
close https://github.com/skaut/Skautske-hospodareni/issues/2401
close https://github.com/skaut/Skautske-hospodareni/issues/2392
=> fix style of buttons

app/AccountancyModule/Components/DataGrid.php
=> Přidán příští rok do filtru DataGridu

frontend/app.scss
=> Opravena barva přepínače dark mode při všech barvách pozadí

frontend/LogoutTimer.ts
=> Opravena chyba v odpočtu přihlášení pro nepřihlášené uživatele

app/AccountancyModule/PaymentModule/components/templates/PaymentList.grid.latte, app/model/Payment/Payment/Transaction.php, migrations/2023/Version20231127061041.php, tests/integration/Infrastructure/Repositories/Payment/PaymentRepositoryTest.php, tests/unit/Payment/PaymentTest.php, tests/unit/Payment/ReadModel/QueryHandlers/RepaymentCandidateListQueryHandlerTest.php
close https://github.com/skaut/Skautske-hospodareni/issues/2302
=> add transaction date to db

app/AccountancyModule/PaymentModule/templates/BankAccounts/detail.latte
Jen drobný fix špatného formátování data vytvoření účtu na přehledu transkací.
=> Fixes bank account creation date formatting

app/AccountancyModule/TravelModule/templates/Contract/detail.latte, app/AccountancyModule/TravelModule/templates/Contract/ex.contract.noz.latte, app/AccountancyModule/TravelModule/templates/Contract/ex.contract.old.latte
https://skautske-hospodareni-of.sentry.io/issues/4943968107/?alert_rule_id=563429&alert_type=issue&notification_uuid=4cc65692-6349-4f9f-af02-4a275e58fc52&project=1328535&referrer=slack
=> fix chronos date

app/AccountancyModule/PaymentModule/components/PairButton.php, app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php, app/model/Payment/Exception/InvalidOAuth.php
=> Paraphrase exception description

app/AccountancyModule/TravelModule/Components/CommandForm.php, app/model/Travel/Command.php, migrations/2024/Version20240422113851.php
Tested that it looks OK in a PDF up to 256 chars.
Closes #2707
=> Widened fellow_passengers to 256 chars instead of 64

app/AccountancyModule/StatisticsModule/templates/Default/default.latte, app/model/Stat/ReadModel/QueryHandlers/CampStatisticsQueryHandler.php, app/model/Stat/ReadModel/QueryHandlers/EventStatisticsQueryHandler.php
Oprava SQL dotazů pro statistiku
=> 2739 doctrinedbalexceptioninvalidfieldnameexception an exception occurred while executing select oskautisid sumciprice as sum

app/model/Travel/TravelService.php
Aktuálně se nevrací žádné platné smlouvy u založení nového cestovního příkazu.
=> fix list of contracts

app/model/Event/ReadModel/QueryHandlers/EducationListQueryHandler.php
Closes #2783 
Neovlivňuje oprávnění, ty řeší zcela jiný systém, tohle PR pouze zobrazí víc typů akcí v seznamu.
=> Show education events even without being in their team

frontend/icons.ts, package.json, yarn.lock
Slučuje všechny dependabot updaty font-awesome do jednoho PR, které tím pádem funguje.
=> Updated font-awesome to 6.6

build.xml
Narazil jsem na to, když jsem dělal nějaký ty aktualizace, že to projde i když ten build selže...
=> Checking return codes in app-init

composer.json, composer.lock
Fixes #2737
Netestoval jsem, netuším, jak.
=> Updated Fio api lib to v5.0

app/AccountancyModule/PaymentModule/components/PairButton.php, app/AccountancyModule/PaymentModule/presenters/BankAccountsPresenter.php, app/model/Bank/BankService.php, app/model/Bank/Exception/BankWrongTokenAccount.php, app/model/Bank/Fio/FioClient.php, app/model/Payment/BankAccountService.php, app/model/Payment/Fio/IFioClient.php
=> Throwing an error when Fio token belongs to the incorrect account

.github/workflows/main.yml, app/config/config.beta.local.neon, build.xml, tests/acceptance/CreateCashbookCest.php
Introduced a new 'deploy-beta' workflow for deploying to beta-h.skauting.cz, including SSH key setup and environment variables. Updated 'deploy-test' workflow formatting for consistency without functional changes. This enhances CI/CD flexibility and deploys to the beta environment.
=> Add beta deployment workflow to GitHub Actions

app/AccountancyModule/PaymentModule/templates/Repayment/default.latte, app/model/Payment/Handlers/Repayment/CreateRepaymentsHandler.php, frontend/app.ts, frontend/ts/checkAll.ts
Uprava js pro hromadný výběr vratek
Zachytávání chyb z fio API
=> 2956 nelze odeslat vetsi mnozstvi vratek
