- app/model/Infrastructure/Repositories/Payment/GroupRepository.php
- app/model/Infrastructure/Repositories/Payment/MailCredentialsRepository.php
- app/model/Payment/Commands/RemoveMailCredentials.php
- app/model/Payment/DomainEvents/MailCredentialsWasRemoved.php
- app/model/Payment/Group.php
- app/model/Payment/MailCredentials/MailProtocol.php
- app/model/Payment/Repositories/IGroupRepository.php
- app/model/Payment/Subscribers/GroupRemovedSubscriber.php
- app/model/Payment/Subscribers/MailCredentialsRemovedSubscriber.php
- tests/integration/Infrastructure/Repositories/Payment/MailCredentialsRepositoryTest.php
- tests/integration/Payment/Handlers/MailCredentials/RemoveMailCredentialsHandlerTest.php
- tests/integration/Payment/UseCases/RemoveGroupTest.php
- tests/integration/Payment/UseCases/RemoveMailCredentialsTest.neon
- tests/integration/Payment/UseCases/RemoveMailCredentialsTest.php
- tests/unit/User/ReadModel/QueryHandlers/EditableUnitsQueryHandlerTest.php
https://sentry.io/organizations/skautske-hospodareni-of/issues/1231069742/events/d3da249a48cc4189acde8e941c596bad/?project=1328535
Po odebrání SMTP zůstalo smtpId nastaveno u skupiny plateb, coz pak zmenoznuje odeslani emailu i editaci skupiny.
> Automatické odebrání vybraného emailu u skupiny při jeho smazání

- frontend/ts/netteForms.ts
- package.json
- yarn.lock
Takhle se nám nebudou rozjíždět verze mezi Nette/Forms používanými v JS a v PHP
> Použití netteForms.js z vendor

- app/AccountancyModule/Components/templates/DataGrid.layout.latte
- app/AccountancyModule/Components/templates/datagrid.latte
- app/AccountancyModule/PaymentModule/templates/GroupList/default.latte
- app/templates/@layout2.latte
Tohle furt není na telefonu dost příjemný, ale aspoň to nerozsype stránku
Ve chvíli, kdy ty prvky jsou pod sebou nedává smysl mít je zarovnaný doprava. To je kvůli tomuto zobrazení:
> Oprava responzivity vybraných prvků

- app/AccountancyModule/PaymentModule/components/GroupForm.php
- app/AccountancyModule/PaymentModule/components/GroupUnitControl.php
- app/model/DTO/Payment/Mail.php
- app/model/DTO/Payment/MailFactory.php
- app/model/Mail/MailService.php
- app/model/Payment/Exception/NoAccessToMailCredentials.php
- app/model/Payment/Group.php
- app/model/Payment/Handlers/Group/ChangeGroupUnitsHandler.php
- app/model/Payment/PaymentService.php
- app/model/Payment/ReadModel/Queries/BankAccount/BankAccountsAccessibleByUnitsQuery.php
- app/model/Payment/ReadModel/Queries/MailCredentials/MailCredentialsAccessibleByGroupsQuery.php
- app/model/Payment/ReadModel/QueryHandlers/BankAccount/BankAccountsAccessibleByUnitsQueryHandler.php
- app/model/Payment/ReadModel/QueryHandlers/MailCredentials/MailCredentialsAccessibleByGroupsQueryHandler.php
- app/model/Payment/Services/IMailCredentialsAccessChecker.php
- app/model/Payment/Services/MailCredentialsAccessChecker.php
- tests/integration/Payment/BankAccountServiceTest.php
- tests/integration/Payment/BankServiceTest.php
- tests/integration/Payment/UseCases/LastPairingInvalidationTest.neon
- tests/integration/Payment/UseCases/LastPairingInvalidationTest.php
- tests/integration/Payment/UseCases/PaymentCompletedEmailTest.neon
- tests/integration/Payment/UseCases/RemoveGroupTest.php
- tests/integration/Payment/UseCases/RemoveMailCredentialsTest.php
- tests/integration/Payment/stubs/MailCredentialsAccessCheckerStub.php
- tests/integration/PaymentServiceTest.neon
- tests/unit/Payment/GroupTest.php
- tests/unit/Payment/Services/MailCredentialsAccessCheckerTest.php
Closes #793
Bankovní účty i maily jsou teď vždy nabízeny podle vazby platební skupiny na jednotky místo podle editovatelných jednotek aktuálního uživatele.
Chování:
- k bankovnímu účtu musí mít přístup všechny jednotky - zde máme obecně striktnější fungování díky možnosti ne/zpřístupnit bankovní účet podjednotkám
- k emailu stačí, aby měla přístup jakákoliv jednotka u skupiny (většina středisek má emaily spravované na úrovni střediska)
> Oprava nabízených bankovních účtů a mailů u platebních skupin s více jednotkami

- app/model/Payment/Payment/Transaction.php
- migrations/2019/Version20191117210220.php
- tests/integration/Infrastructure/Repositories/Payment/PaymentRepositoryTest.php
- tests/unit/BankServiceTest.php
spadlo mi párování na locale vůči ostrému účtu, protože číslo transakce je vyšší než int
> use transaction_id as a string

- app/AccountancyModule/PaymentModule/presenters/BankAccountsPresenter.php
- app/AccountancyModule/PaymentModule/templates/BankAccounts/detail.latte
close #816 
zobrazuje název skupiny ve které je to spárované, pokud máš právo na čtení dané skupiny.
> show payment group name on paired payment

- app/AccountancyModule/Components/FormControls/DateControl.php
- app/AccountancyModule/EventModule/templates/NewEvent/default.latte
- app/AccountancyModule/PaymentModule/components/GroupForm.php
- app/AccountancyModule/PaymentModule/components/MassAddForm.php
- app/AccountancyModule/PaymentModule/components/PaymentDialog.php
- app/AccountancyModule/PaymentModule/presenters/RepaymentPresenter.php
- frontend/ts/datePicker.ts
Closes https://github.com/skaut/Skautske-hospodareni/issues/1154
Kromě toho jsem (v samostatném commitu) upravil nadpis u přidávání nové akce. Bylo tam "Nová výprava" - všude jinde používáme "Akce". Stejně se název používá i ve Skautisu.
> Oprava neaktivního víkendu v datepickeru u akcí a cesťáků

- composer.json
- composer.lock
- tests/integration.suite.yml
contributte/codeception je nástupce původního balíčku.
Tento PR navíc nahrazuje https://github.com/skaut/Skautske-hospodareni/pull/1052
> Nahrazení arachne/codeception za contributte/codeception

- tests/unit/Cashbook/Cashbook/AmountTest.php
Opravil jsem jeden test, který očividně používal špatný data provider. Ten totiž [po aktualizaci Codeception](https://github.com/skaut/Skautske-hospodareni/pull/1188) přestal kvůli nekompatibilním typům fungovat
> Oprava data provideru v AmountTest::testIsUsingFormula()

- app/model/Cashbook/ICategory.php
- app/model/Cashbook/ParticipantType.php
- app/model/Cashbook/ReadModel/CategoryTotalsCalculator.php
- app/model/Cashbook/ReadModel/QueryHandlers/CategoryListQueryHandler.php
- app/model/Export/ExportService.php
- app/model/Export/templates/campReport.latte
- migrations/2020/Version20200112173514.php
- tests/unit/Cashbook/ReadModel/CategoryTotalsCalculatorTest.php
close #982
Historické táborové vratky jsou přesunuty jako dětské v rámci migrace.
> Rozdělení táborových vratek pro děti a dospělé

- frontend/ts/ajax.ts
Na velkých* stránkách se nepodaří Naja uložit stránku přes History API, které jinak stejně nepoužíváme.
To vede k chybě, kvůli které se nezpracuje nic dalšího, takže na stránce například nejsou ikony.
\* velká stránka je např. detail skupiny s 64+ platbami. U registrací a plesu jsem na to teď několikrát narazil. Menší stránky jsou ok.
> Oprava JS na "velkých stránkách"

- tests/_support/IntegrationTest.php
- tests/integration/Cashbook/CashbookIntegrationTest.php
- tests/integration/Cashbook/Handlers/MoveChitsToDifferentCashbookHandlerTest.php
- tests/integration/Cashbook/Handlers/Unit/CreateCashbookHandlerTest.php
- tests/integration/Cashbook/Handlers/Unit/CreateUnitHandlerTest.php
- tests/integration/Cashbook/ReadModel/QueryHandlers/ChitListQueryHandlerTest.php
- tests/integration/Infrastructure/Repositories/Budget/CategoryRepositoryTest.php
- tests/integration/Infrastructure/Repositories/Cashbook/CashbookRepositoryTest.php
- tests/integration/Infrastructure/Repositories/Cashbook/StaticCategoryRepositoryTest.php
- tests/integration/Infrastructure/Repositories/Cashbook/UnitRepositoryTest.php
- tests/integration/Infrastructure/Repositories/Logger/LogEntryRepositoryTest.php
- tests/integration/Infrastructure/Repositories/Payment/BankAccountRepositoryTest.php
- tests/integration/Infrastructure/Repositories/Payment/GroupRepositoryTest.php
- tests/integration/Infrastructure/Repositories/Payment/MailCredentialsRepositoryTest.php
- tests/integration/Infrastructure/Repositories/Payment/PaymentRepositoryTest.php
- tests/integration/Infrastructure/Repositories/Travel/CommandRepositoryTest.php
- tests/integration/Infrastructure/Repositories/Travel/ContractRepositoryTest.php
- tests/integration/Infrastructure/Repositories/Travel/VehicleRepositoryTest.php
- tests/integration/Payment/BankAccountServiceTest.php
- tests/integration/Payment/BankServiceTest.php
- tests/integration/Payment/Handlers/MailCredentials/CreateMailCredentialsHandlerTest.php
- tests/integration/Payment/Handlers/MailCredentials/RemoveMailCredentialsHandlerTest.php
- tests/integration/Payment/ReadModel/QueryHandlers/CountGroupsWithBankAccountQueryHandlerTest.php
- tests/integration/Payment/ReadModel/QueryHandlers/PairedPaymentsQueryHandlerTest.php
- tests/integration/Payment/UseCases/LastPairingInvalidationTest.php
- tests/integration/Payment/UseCases/PaymentCompletedEmailTest.php
- tests/integration/Payment/UseCases/RemoveGroupTest.php
- tests/integration/Payment/UseCases/RemoveMailCredentialsTest.php
- tests/integration/PaymentServiceTest.php
Momentálně přidání nové entity do agregátu znamená to, že je ve všech integračních testech, kde se s daným agregátem nějak pracuje, potřeba doplnit třídu entity do `getTestedEntites()`, aby se pro ně v testech vytvořily tabulky. To je dost opruz a jde to vyřešit jednodušeji.
Proto jsem z jiného projektu převzal řešení, kdy stačí vyjmenovat AR/hlavní entitu a zbytek entit se automaticky dohledá.
> Automatické dohledávání entit z agregátu v testech

- .docs/nastroje.md
- frontend/app.scss
- frontend/app.ts
- frontend/scss/pikaday.scss
- package.json
- postcss.config.js
- webpack.config.js
- yarn.lock
V používání se nic nemění - aplikuje se stále autoprefixer atd, jen to všechno proteče Webpackem.
To znamená, že není potřeba ručně buildovat, ale stačí nechat běžet `yarn build --watch` a JS/CSS se přegeneruje, když se nějaký TS/SCSS soubory změní.
> Kompilace SASS -> CSS přes Webpack

- app/AccountancyModule/EventModule/presenters/DefaultPresenter.php
- app/model/Auth/Resources/Event.php
Opravuje https://sentry.io/organizations/skautske-hospodareni-of/issues/1465067836/?project=1328535&query=is%3Aunresolved
Checkovali jsme možnost smazat akci (což neděláme nikde), nikoliv zrušit akci. Takže šlo volat zrušení na už zrušených akcích.
> Oprava kontroly, zda lze zrušit akci

- wercker.yml
> Použití MySQL 8.0 pro vývoj

- build.xml
Použití správné verze PHP na Lebedě při deploymentu.
Nejdříve musí být přidáno na Lebedě.
> Použití správné verze PHP na Lebedě při deploymentu

- app/AccountancyModule/CampModule/Components/ExportDialog.php
- app/AccountancyModule/CampModule/Components/templates/ExportDialog.latte
- app/AccountancyModule/Components/Dialog.php
- app/AccountancyModule/Components/templates/Dialog.layout.latte
- app/AccountancyModule/EventModule/components/ExportDialog.php
- app/AccountancyModule/EventModule/components/templates/ExportDialog.latte
- app/AccountancyModule/PaymentModule/components/PaymentDialog.php
- app/AccountancyModule/PaymentModule/components/RemoveGroupDialog.php
- app/AccountancyModule/PaymentModule/components/SmtpUpdateForm.php
- app/AccountancyModule/PaymentModule/components/templates/PaymentDialog.latte
- app/AccountancyModule/PaymentModule/components/templates/RemoveGroupDialog.latte
- app/AccountancyModule/PaymentModule/components/templates/SmtpUpdateForm.latte
- app/AccountancyModule/TravelModule/Components/EditTravelDialog.php
- app/AccountancyModule/TravelModule/Components/templates/EditTravelDialog.latte
- tests/_support/Page/Payment.php
V aplikaci máme docela dost modálů, které si však vždy implementují životní cyklus dialogu (zobrazování x skrývání). Pokusil jsem se to dostat na jedno místo.
---
Ty změny jsou v podstatě snadný - vznikla nová šablona Dialog.layout.latte ve které je normální bootstrap modál, kterej má obsah .modal-body, .modal-title, .modal-footer jako bloky dialog-body, dialog-title, resp. dialog-footer.
Takže všechny dialogy (z nového designu), které předtím vypadaly:
```latte
<div n:snippet n:inner-if="$renderModal" class="modal" tabindex="-1" role="dialog">
<div class="modal-dialog" role="document">
<div class="modal-content">
<div class="modal-header">
<h5 class="modal-title">Nějaký titulek</h5>
<button type="button" class="close" data-dismiss="modal" aria-label="Close">
<span …
```
> Abstrakce pro modální dialogy

- .github/workflows/main.yml
- app/config/model/doctrine.neon
- app/model/Budget/Category.php
- app/model/Cashbook/Cashbook/Chit.php
- app/model/Cashbook/Category.php
- app/model/Cashbook/Category/ObjectType.php
- app/model/Infrastructure/Types/MoneyType.php
- app/model/Logger/LogEntry.php
- app/model/Participant/Payment.php
- migrations/2020/Version20200214111513.php
- migrations/2020/Version20200214114359.php
- migrations/2020/Version20200214130535.php
- migrations/2020/Version20200406114332.php
- tests/integration/Cashbook/CashbookIntegrationTest.php
- tests/integration/Infrastructure/Repositories/Travel/CommandRepositoryTest.php
Část https://github.com/skaut/Skautske-hospodareni/issues/880, po mergnutí navážu ještě jedním PR se sjednocením názvů sloupců a indexů.
Změny, které stojí za zmínit:
- **Enumy jsou mapované jako varchar místo MySQL enumů** - alternativou je buď psát u sloupců vždy vlastní columnDefinition (kde musíme znát všechny hodnoty enumů), nebo definování vlastního typu pro daný enum
- **Money objekty jsou mapovány jako INT v centech** (tedy *25,50 Kč* se místo `25.5` mapuje jako `2550` - k tomu jsem přistoupil proto, že by alternativou byla potřeba ručního nastavování `precision` a `scale` u všech properties, které by měly `type="money"`
- **`TravelType::$price` a `VehicleType::$distance` jsou mapované jako samostatné sloupce** - tím, že je teď Money mapovaný jako INT, tak by `MoneyType` musel …
> Sjednocení mapování a databáze

- app/AccountancyModule/Components/Cashbook/templates/ChitListControl.topPanel.latte
> Sloučení exportovacích tlačítek pro pokladní knihu

- app/AccountancyModule/Components/Cashbook/ChitListControl.php
- app/AccountancyModule/Components/Cashbook/templates/ChitListControl.latte
- app/AccountancyModule/Components/Cashbook/templates/ChitListControl.topPanel.latte
- app/AccountancyModule/Components/Cashbook/templates/MoveChitsDialog.latte
- odebrán ajax, protože se pak neposílají soubory s hromadnými exporty
- tlačítko upraveno na btn-sm (btn-xs již neexistuje)
- skrytí devideru, pokud tam není položka v první sekci
> Oprava drobností v pokladní knize

- app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php
- app/AccountancyModule/PaymentModule/templates/Payment/default.latte
Tohle je pozůstatek stavu `odesláno` u plateb. Zobrazovali jsme v UI počet všech plateb, které byly ve stavu `připravena`, abychom uživatele upozornili, že má ještě rozeslat emaily.
Každopádně s tím, jak jsem předělal odesílání mailů tak, že momentálně platby zůstávají ve stavu `připravena` a emaily se evidují jako kolekce u plateb, došlo k tomu, že to číslo v UI nesedělo - počítalo všechny `připravené` platby jako neodeslané.
> Oprava počítání plateb bez odeslaného emailu

- app/AccountancyModule/PaymentModule/components/MassAddForm.php
V případě, že je zadaná výchozí částka, tak lze zadat 0 jako platbu a to pak následně vychodí chybu na neplatný argent, že amount má být větší než 0.
> Oprava kontoly částky u platby

- app/AccountancyModule/Components/Participants/ParticipantList.php
Nakonec se ukázalo, že tam někdy příjde prázdný string a někdy null, tedy je potreba řešit oba případy. 
https://sentry.io/organizations/skautske-hospodareni-of/issues/1722075639/?project=1328535&referrer=slack
> Oprava hromadné editace účastníků

- app/model/Excel/ExcelService.php
Při exportu seznamu účastníků tábora byl sloupec obsahující přezdívky účastníků nadepsán *Příjmení*, místo *Přezdívka*.
> Oprava chybného názvu sloupce

- app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php
Dle té hlášky, co se na základě `$notSentPaymentsCount` vypisuje soudím, že to má být takto (a nebo je špatně ta hláška).
**POZOR** absolutně netestováno, nepodařilo se mi poslední verzi Hospodaření uchodit lokálně.
> Fix notSentPaymentsCount

- tests/_support/AcceptanceTester.php
Momentálně se zdá, že akceptační testy občas běží natolik rychle, že se pokusí ve Skautisu hledat text přihlášení ještě předtím než se načte ten webfont. Takže ten tester nevidí daným text a failne.
P.S. On je to teda i "fail" Skautisu, že nemá fallback na standardní font, takže na pomalém připojení nejdřív problikne obrazovka kompletně bez textů.
Tohle by mělo fixnout (alespoň část z nich) situace, kdy akceptační testy náhodně padají.
> Oprava failujících akceptačních testů po přístupu na přihlašovací stránku

- app/model/Payment/MailingService.php
Tohle bude pro spoustu lidí první místo, kde se dozví o tom, že už SMTP emaily nefungují, tak by to mělo být korektně odhchytnuto.
Opravuje https://sentry.io/organizations/skautske-hospodareni-of/issues/2041326770/?project=1328535&query=is%3Aunresolved
> Oprava odchytávání výjimky při nevyplněném emailu u skupiny plateb

- app/config/model/doctrine.neon
Opravuje https://sentry.io/organizations/skautske-hospodareni-of/issues/2062354608/?project=1328535&referrer=slack
To je command, kterej jsem v appce nenašel, protože se používá jen při deploymentu - tohle tedy opravuje deployment.
> Registrace dvou používaných ORM příkazů do konzole

- app/AccountancyModule/MyValidators.php
- app/AccountancyModule/PaymentModule/components/MassAddForm.php
- app/AccountancyModule/PaymentModule/components/PaymentDialog.php
- app/AccountancyModule/PaymentModule/components/templates/MassAddForm.latte
- app/AccountancyModule/PaymentModule/components/templates/PaymentDialog.latte
- app/AccountancyModule/PaymentModule/components/templates/PaymentList.grid.latte
- app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php
- app/config/model/doctrine.neon
- app/model/DTO/Payment/EmailAddress.php
- app/model/DTO/Payment/Payment.php
- app/model/DTO/Payment/PaymentFactory.php
- app/model/Infrastructure/Types/EmailAddressType.php
- app/model/Payment/Commands/Payment/CreatePayment.php
- app/model/Payment/Commands/Payment/UpdatePayment.php
- app/model/Payment/Handlers/Payment/CreatePaymentHandler.php
- app/model/Payment/Handlers/Payment/UpdatePaymentHandler.php
- app/model/Payment/Mailing/Payment.php
- app/model/Payment/MailingService.php
- app/model/Payment/Payment.php
- app/model/Payment/Payment/EmailRecipient.php
- migrations/2020/Version20201128164940.php
- tests/integration/Payment/BankServiceTest.php
- tests/integration/Payment/UseCases/LastPairingInvalidationTest.php
- tests/integration/Payment/UseCases/PaymentCompletedEmailTest.php
- tests/integration/Payment/UseCases/RemoveGroupTest.php
- tests/integration/PaymentServiceTest.php
- tests/unit/BankServiceTest.php
- tests/unit/DTO/Payment/EmailAddressTest.php
- tests/unit/Payment/Group/EmailTemplateTest.php
- tests/unit/Payment/PaymentTest.php
close #1219
- Užilo by to hezčí UI, ale to bych řešil až časem separátně, aby to neblokovalo funkcionalitu.
- až se to celé ověří v běhu, tak odeberu nepoužívaný email, obdobně jako SMTP.
> Umožnit více příjemců emailů u plateb

- app/AccountancyModule/PaymentModule/components/MassAddForm.php
Tohle je IMO bug, který vznikl v důsledku přidání možnosti výběru více emailů u platby.
Předtím byl defaultně vybrán první email, teď to není žádný - pro uživatele, který tak používá hskauting jednou ročně pro registrace je to tak změna, která není na první pohled patrná (vanilla multi selectbox není moc uživatelsky známej) a vyústí v to, že si naimportuje platby bez emailů.
Tohle obnovuje chování, které tam bylo předtím - defaultně je vybrán první z emailů. IMO by dávala smysl i varianta automaticky předvybrat všechny, pokud ti to přijde jako lepší varianta @sinacek .
> Defaultní vybrání prvního emailu u hromadného importu plateb

- app/model/Infrastructure/Log/Sentry/UserContextEventProcessor.php
Chyba vzniklá při aktualizaci Sentry (#1548) - ten user je defaultně null, takže na něm není možné volat tu továrnu.
> Oprava error reportingu

- app/AccountancyModule/PaymentModule/components/GroupUnitControl.php
aktuálně doplnujeme jen oficial unit a přímé pod jednotky (oddíly), ale chybí tam družina. Vzhledem k tomu, ze to zatím nikdo nepotreboval, tak to přidávám jen pokud je to explicitně poptávané. 
Řeší https://sentry.io/organizations/skautske-hospodareni-of/issues/2347818429/?referrer=slack
> Přidání chybějící jednotky

- app/model/Event/Education.php
- app/model/Event/Factory/EducationFactory.php
řeší https://sentry.io/organizations/skautske-hospodareni-of/issues/2508548333/?project=1328535&referrer=slack
Danou položku `ID_EventEducationState` mi skautis nevrací a ani jsem nenašel, že by se někde nakonec používala, tak ji odebírám.
> Odebrání state ve vzdělávačkách

- app/AccountancyModule/presenters/CashbookExportPresenter.php
řeší chybu https://sentry.io/organizations/skautske-hospodareni-of/issues/2614820475/?project=1328535&referrer=slack
konrektně problém s názvem: Potraviny stavěčka (Duha, Břoušek)
> Převedení pdf názvů souborů v zip na ASCII

- app/config/components.neon
- app/config/config.neon
- composer.json
- composer.lock
Tím, že jsme na Nette 3 už není potřeba používat moje 3rd-party extension a můžeme
pro automatickou registraci služeb použít [SearchExtension](https://doc.nette.org/en/3.0/di-configuration#toc-search), které je přímo součástí `nette/di`.
> Odebrání AutoDI

- app/model/Infrastructure/Types/TransportTypeListType.php
- app/model/Travel/Command.php
- app/model/Travel/TravelService.php
Tohle je obecně častej bug v PHP. Zvážil bych, jestli pak nepřidat třeba Psalm, kterej je schopen rozlišovat mezi `list<T>` jako seznamem a `array<K, V>` jako asociativním polem
Opravuje https://sentry.io/organizations/skautske-hospodareni-of/issues/2788714494/ pro nové záznamy. Aktuální v DB už fixoval @sinacek
> Oprava špatně serializovaného seznamu dopravních prostředků

- composer.json
- composer.lock
Kontroloval jsem i [deklarované BC breaky](https://github.com/cakephp/chronos/releases/tag/2.0.0) a není tam nic, co by nás zasáhlo.
Tohle by dependabot nepořešil, protože se navzájem blokoval update těch dvou aktualizovaných knihoven.
> Aktualizace cakephp/chronos

- app/model/Payment/Payment.php
- migrations/2021/Version20211121182733.php
- tests/integration/Infrastructure/Repositories/Payment/PaymentRepositoryTest.php
Tohle je pozůstatek z #1517, ta property se nikde nepoužívá a původní data z ní byla přemigrována do té nové entity `EmailRecipient`
> Odebrání nepoužívané property `Payment::$email`

- app/AccountancyModule/EventModule/presenters/CashbookPresenter.php
- app/model/Budget/Category.php
- app/model/Cashbook/Cashbook/Chit.php
- app/model/Cashbook/Cashbook/ChitScan.php
- app/model/Excel/Builders/CashbookWithCategoriesBuilder.php
- app/model/Payment/Group/Email.php
- app/model/Payment/Group/Unit.php
- app/model/Payment/Payment/EmailRecipient.php
- app/model/Payment/Payment/SentEmail.php
- app/model/Travel/Command.php
- app/model/Travel/Vehicle/RoadworthyScan.php
- composer.json
- composer.lock
- migrations/2021/Version20211121183832.php
- phpstan.neon
- tests/object-manager.php
Tohle by nedokázal dependabot sám pořešit, protože to byly 3 balíčky, které se navzájem blokovali v aktualizaci
Closes https://github.com/skaut/Skautske-hospodareni/pull/1719
Closes https://github.com/skaut/Skautske-hospodareni/pull/1729
---
Za zmínku stojí to, že momentálně máme kontrolované i mapování entit (tam jsem pofixoval pár problémů s `|null`)
> Aktualizace PHPStan na 1.2

- app/model/Cashbook/ReadModel/QueryHandlers/Pdf/ExportChitsHandler.php
- app/model/Cashbook/ReadModel/QueryHandlers/Pdf/templates/chits.out.latte
- app/model/Unit/Services/Unit.php
Přidává nedělitelnou mezeru, pro správné zalomení v hlavičce dokladu
**Původně**
**Nově**
> add non breaking space to chits

- app/AccountancyModule/PaymentModule/templates/Payment/massAdd.latte
Probably copy&pasted from the default.latte
'osoby neměly'
> Typo in a user-facing text.

- .github/dependabot.yml
Vzhledem k tomu, že už asi rok prakticky nereviewuji žádné PR, tak mi nedává smysl být jako výchozí reviewer pro PR otevřené dependabotem. Jediné, co to realně znamená, že každy týden musím promazat asi 10 mailů. :grinning:
> Odebrání @fmasa z výchozích reviewerů pro Dependabota

- app/AccountancyModule/CampModule/templates/Budget/default.latte
Ten tooltip byl naopak, to, co se v něm zobrazuje je částka v ISu, součet paragonů je v tabulce
closes #2312
> Fixed incorrect inconsistency tooltip in Camp budget

- app/AccountancyModule/EducationModule/presenters/BasePresenter.php
- app/model/Auth/Resources/Education.php
Podle mě se tam načítaly špatný oprávnění, prosím o kontrolu...
Closes #2313
> Fixed Education presenter checking general event update permission instead of Education event update permission

- app/model/Cashbook/ReadModel/CategoryTotalsCalculator.php
- migrations/2023/Version20231008115940.php
> Přidána jednotná kategorie vratek účastnických poplatků pro vzdělávačky

- app/AccountancyModule/EducationModule/presenters/PrivilegesPresenter.php
- app/AccountancyModule/EducationModule/templates/@layout.new.latte
- app/AccountancyModule/EducationModule/templates/Privileges/default.latte
- app/AccountancyModule/EducationModule/templates/header.latte
@sinacek prosím o kontrolu, tady si dost nejsem jistej, jestli to popisuju správně...
Closes #2322
Konflikt s následujícími PR - bude potřeba tahle oprávnění taky přidat do seznamu:
> Zobrazování oprávnění pro vzdělávačky

- app/AccountancyModule/Components/LoginPanel.php
- tests/_support/AcceptanceTester.php
Před:
Po:
Closes #2363. Ty role jsou podle mě zbytečně složitý, ale SkautIS to prý měnit nebude. A parsovat si to z toho sám fakt nechci...
Mimochodem pro tábory je to podle mě taky upgrade...
> Zobrazování celých názvů rolí

- app/AccountancyModule/EducationModule/EducationListDataSource.php
- app/AccountancyModule/EducationModule/presenters/BudgetPresenter.php
- app/AccountancyModule/EducationModule/presenters/CashbookPresenter.php
- app/AccountancyModule/EducationModule/presenters/EducationPresenter.php
- app/model/Cashbook/Education.php
- app/model/Cashbook/ReadModel/Queries/EducationCashbookIdQuery.php
- app/model/Cashbook/ReadModel/Queries/EducationParticipantCategoryIdQuery.php
- app/model/Cashbook/ReadModel/Queries/InconsistentEducationCategoryTotalsQuery.php
- app/model/Cashbook/ReadModel/Queries/SkautisEducationYearQuery.php
- app/model/Cashbook/ReadModel/QueryHandlers/EducationCashbookIdQueryHandler.php
- app/model/Cashbook/ReadModel/QueryHandlers/EducationParticipantCategoryIdQueryHandler.php
- app/model/Cashbook/ReadModel/QueryHandlers/InconsistentEducationCategoryTotalsQueryHandler.php
- app/model/Cashbook/ReadModel/QueryHandlers/SkautisEducationYearQueryHandler.php
- app/model/Cashbook/Repositories/CategoryRepository.php
- app/model/Cashbook/Repositories/IEducationCategoryRepository.php
- app/model/Cashbook/Repositories/IEducationRepository.php
- app/model/Export/ExportService.php
- app/model/Infrastructure/Repositories/Cashbook/EducationRepository.php
- app/model/Skautis/Cashbook/EducationCategoryUpdater.php
- app/model/Skautis/Cashbook/Repositories/EducationCategoryRepository.php
- migrations/2023/Version20231025231859.php
- Opravuje SkautISovou chybu při načítání kategorií vzdělávačky
- Pokladní knihy vzdělávaček se nově ukládají pro kombinaci vzdělávačka + rok
- Za rok vzdělávačky se bere vždy rok jejího posledního dne
- Trochu pokládá základy pro #2331 - v rovině databáze a ukládání pokladních knih, co se UI týče, tak vůbec.
fixes H-SKAUTING-CZ-1GT
> Pokladní knihy vzdělávaček a jejich kategorie specifické pro rok

- app/model/DTO/Payment/PaymentFactory.php
close https://skautske-hospodareni-of.sentry.io/issues/4658577363/?alert_rule_id=563429&alert_type=issue&notification_uuid=909bbe9d-db71-4a84-bd54-961a1a07861a&project=1328535&referrer=slack
User Deprecated: 2.5 instance() will be removed in 3.x.
> replace deprecated instance()

- app/model/Payment/Handlers/Repayment/CreateRepaymentsHandler.php
Z oficiální informace banky (https://www.fio.cz/bankovni-sluzby/api-bankovnictvi):
> Aktuálně: Měníme adresu API Bankovnictví
>
> Z důvodu větší bezpečnosti dochází k přesunu domény Fio API Bankovnictví ze stávající https://www.fio.cz/ib_api/ na samostatnou URL https://fioapi.fio.cz/. Po přechodné období 6 měsíců budou platné obě výše uvedené adresy (do 30. 11. 2024).
> 
> Co to pro vás znamená?
> Pokyny zasílané z API Bankovnictví je třeba začít směřovat na novou URL, tedy:
> 
>  upravit import (upload) platebních příkazů do banky: https://www.fio.cz/ib_api/rest/import/ >  https://fioapi.fio.cz/v1/rest/import/,
>    analogicky upravit export pohybů a výpisů z banky k vám (viz dokumentace níže).
>
> Pro klienty Fio API Plus brzy zveřejníme novou verzi aplikace s aktualizovanou URL
> Změna endpointu FIO API
